name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        iqta_branch:
          - pip-install-binary-only
          - remove-VSCMD_ARG_TGT_ARCH
          - use-python-3_6-or-3_7        
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'pzhlkj6612/install-qt-action'
          ref: '${{ matrix.iqta_branch }}'

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: "npm ci"
        run: npm ci

      - name: "npm run build"
        run: |
          npm run build-setup-python
          npm run build

      - env:
          VSCMD_ARG_TGT_ARCH: 'x86'
        uses: ./
        with:
          version: 5.14.2
          arch: win32_msvc2017
