name: CI

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/default-empty-py7ze-version.yml
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/default-empty-py7ze-version.yml

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - env:
          VSCMD_ARG_TGT_ARCH: 'x86'
        uses: pzhlkj6612/install-qt-action@default-empty-py7ze-version
        with:
          version: 5.14.2
          arch: win32_msvc2017
